### PR TITLE
Add additional installation instructions for first-time users of Dock…

### LINKED ISSUE #27: Update installation instructions for first-time users of Docker
When following the step-by-step [installation instructions](https://github.com/commonsearch/cosr-front/blob/master/INSTALL.md), the `make docker_pull` step fails, since the Docker daemon has not yet been started.

To make it easier for first-time users of Docker to jump straight in, add an additional step prior to the `make docker_pull` step, which describes how to start the Docker daemon.

The error reported if the Docker is not yet started is as follows.

```
u@x1 ~/g/s/g/c/cosr-front> make docker_pull
docker pull commonsearch/local-front
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon. Is the docker daemon running on this host?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
Makefile:133: recipe for target 'docker_pull' failed
make: *** [docker_pull] Error 1
```

### PR DESCRIPTION
**Pull request by mewmew**
…er. Fixes #27.

### CODE REVIEW

**Comment by mewmew** [comment]
This pull request was sent out prematurely. It turns out that aliases are ignored by `make`, or rather only used by interactive terminal environments. In either case, the described solution does not fix the initial problem.

**Comment by sylvinus** [comment]
Thanks for the PR! I'm sure there is a way to make it work for all users.

I agree that there should be a bit on making sure the docker daemon is started, ideally with links to the right places in the docker documentation for each platform, to avoid duplicating too much on our end!

**Comment by mewmew** [comment]
> I agree that there should be a bit on making sure the docker daemon is started, ideally with links to the right places in the docker documentation for each platform, to avoid duplicating too much on our end!

I agree. Avoiding duplication is good, while making sure most users never even have to click the links, by including the minimal set of commands to get them up and running.

The official docker documentation is good, but does not mention any alternative solutions to mitigate the security implications of adding your user the `docker` group as far as I'm aware. That's why I added the alias solution (which turned out not to be working in the end).

@sylvinus, thanks for taking the lead to create a really wonderful project! It is a very important issue you are trying to solve, as I'm sure you are already aware. And it looks like others are starting to see the dangers of proprietary ranking algorithms as well https://aeon.co/essays/how-the-internet-flips-elections-and-alters-our-thoughts

Best of luck in your future efforts! :) I'll try to follow the development of Common Search and hopefully contribute in one way or another.

Cheers
/u

**Comment by sylvinus** [comment]
Thanks @mewmew! Now that you have a working local install I definitely hope you can contribute more :)

**Pull request closed without merging**
